version: "3.7"

services:
  influxdb:
    image: bitnami/influxdb:1.8.5
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8085:8088"
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=hoplin1234!
      - INFLUXDB_ADMIN_USER_TOKEN=hoplin1234!
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_DB=k6db
    volumes:
      - ./influx-setup.sh:/docker-entrypoint-initdb.d/init_influxdb.sh
  granafa:
    image: bitnami/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - ./provisioning/datasource:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboard:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
